#Build
FROM node:16 as build-step
WORKDIR /app
COPY [ "angular.json", "tsconfig.json", "tsconfig.app.json", "package.json", "./"]
RUN npm i

COPY ["src/", "src/"]
RUN  npm run build

  #Runtime
FROM nginx:1.12.2

WORKDIR /app

COPY  --from=build-step ["/app/node_modules/", "/app/node_modules/"]
COPY  --from=build-step ["/app/dist/", "/app/dist/"]
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html
RUN ln -s /app/dist/ /usr/share/nginx/html
